# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Example config for apigee-remote-service-envoy configuration in SaaS.
# You should generate your config using the CLI.
apiVersion: v1
kind: ConfigMap
metadata:
  name: apigee-remote-service-envoy
  namespace: apigee
data:
  config.yaml: |
    tenant:
      internal_api: https://istioservices.apigee.net/edgemicro
      remote_service_api: https://org.apigee.net/istio-auth
      org_name: org
      env_name: env
      key: NotReal
      secret: NotReal
    products:
      refresh_rate: 2m
    analytics:
      file_limit: 1024
      collection_interval: 10s
    auth:
      api_key_cache_duration: 30m
      api_key_claim:
